services:
  backend:
    container_name: backend
    image: directus/directus:11.0.1
    ports:
      - "8055:8055"
    volumes:
      - ./backend/uploads:/directus/uploads
      - ./backend/extensions:/directus/extensions
      - ./backend/templates:/directus/templates
    environment:
      SECRET: ${SECRET}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_AUTO_PURGE: ${CACHE_AUTO_PURGE}
      CACHE_STORE: ${CACHE_STORE}
      REDIS: ${REDIS}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # PUBLIC_URL: ${PUBLIC_URL}
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - hypericum

  db:
    container_name: db
    image: postgis/postgis:12-master # Downgrade to PostgreSQL 12
    platform: linux/amd64 # for platform error on Apple M1 chips
    volumes:
      - hypericum-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    networks:
      - hypericum

  cache:
    container_name: cache
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    networks:
      - hypericum

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: frontend:latest
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/svelte.config.js:/app/svelte.config.js
    ports:
      - "5173:5173" # Adjust if your Vite config uses a different port
    networks:
      - hypericum

volumes:
  hypericum-data:

networks:
  hypericum:
    name: hypericum
    driver: bridge
